### ISSUE TITLE
[Bug] BetterScreenshare 

### ISSUE THREAD

**Issue by Loukious** [philhk/Vencord#6]
### What happens when the bug or crash occurs?

There seem to be a desync problem with the audio being ahead of the stream. I've tried it with different encoders, HW acceleration on/off and other discord settings but it's always there. Disabling the plugin fixes the issue.

### What is the expected behaviour?

Video and audio in sync.

### How do you recreate this bug or crash?

Stream and let someone watch it to confirm the delay
These are my settings:
<img width="710" alt="image" src="https://github.com/philhk/Vencord/assets/24696530/9ee6e8ac-b15e-4465-9442-45f869226e8b">

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by philhk** [comment]
The audio and video desynchronization issue you are facing could be because either your internet connection or your encoder isn't keeping up. WebRTC sends two distinct streams for audio and video. If the video's bitrate is too high, it can result in delayed audio. You've set the Keyframe Interval to 1, so consider changing it to 30 or turning it off entirely, as this setting might be the reason.
